# Generated by Django 2.1.7 on 2019-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='method',
            new_name='type',
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='empty', max_length=150, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=254, verbose_name='值'),
        ),
    ]
